name: Deploy to Amazon Web Services EC2

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm' # Cache npm packages

      - name: Install dependencies with npm
        run: npm install

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Install pm2
        run: npm i -g pm2

      - name: Restart pm2 Job
        run: pm2 restart server --update-env
